"""Application-wide constants — mirrored from the original TypeScript project."""

# Planting-mode growth factors by simulation year
TREE_GROWTH_FACTORS = {
    "YEAR_1": 0.05,
    "YEAR_2": 0.15,
    "YEAR_3": 0.30,
    "YEAR_4": 0.50,
    "YEAR_5": 0.70,
    "YEAR_6_TO_10": 0.80,
    "YEAR_11_TO_20": 0.90,
    "YEAR_20_PLUS": 1.00,
}

# Clear-cutting: growth factors by existing tree age
TREE_AGE_GROWTH_FACTORS = {
    "AGE_1": 0.05,
    "AGE_2": 0.15,
    "AGE_3": 0.30,
    "AGE_4": 0.50,
    "AGE_5": 0.70,
    "AGE_6": 0.85,
    "AGE_7_TO_20": 0.95,
    "AGE_21_TO_50": 0.90,
    "AGE_50_PLUS": 0.85,
}

CARBON_CONVERSION = {
    "CARBON_TO_CO2": 3.67,
    "SOIL_CARBON_MODIFIER": 0.1,  # kg CO2/year per g/kg of soil carbon
    "KG_TO_METRIC_TONS": 1000,
}

ENVIRONMENTAL_MODIFIERS = {
    "PRECIPITATION_TO_RESILIENCE": 0.001,
    "TEMPERATURE_CHANGE_FACTOR": 0.02,
    "PRECIPITATION_CHANGE_FACTOR": 0.0001,
}

WATER_RETENTION = {
    "BASE_RATE": 70,
    "ANNUAL_IMPROVEMENT": 0.3,
    "ANNUAL_DEGRADATION": 0.5,
    "MAX_RETENTION": 95,
}

AIR_QUALITY = {
    "BASE_QUALITY": 60,
    "ANNUAL_IMPROVEMENT": 0.7,
    "ANNUAL_DEGRADATION": 1.0,
    "MAX_IMPROVEMENT": 95,
    "MAX_DEGRADATION": -80,
}

IMPACT_CAPS = {
    "MAX_BIODIVERSITY": 5.0,
    "MIN_BIODIVERSITY": 0.0,
    "MAX_RESILIENCE": 5.0,
    "MIN_RESILIENCE": 0.0,
    "BIODIVERSITY_TIME_BONUS": 0.05,
    "RESILIENCE_TIME_BONUS": 0.03,
}

SOCIAL_IMPACT = {
    "PLANTING_BASE_SCORE": 3.5,
    "CLEAR_CUTTING_BASE_SCORE": 2.0,
    "TREE_DIVERSITY_MULTIPLIER": 0.2,
    "TREE_DIVERSITY_PENALTY": 0.1,
    "TIME_MULTIPLIER_PLANTING": 0.02,
    "TIME_MULTIPLIER_CLEARING": 0.01,
    "AREA_MULTIPLIER_PLANTING": 0.1,
    "AREA_MULTIPLIER_CLEARING": 0.05,
    "MAX_DIVERSITY_BONUS": 1.0,
    "MAX_TIME_BONUS": 1.0,
    "MAX_AREA_BONUS": 1.0,
    "MAX_SCORE": 5.0,
    "MIN_SCORE": 1.0,
}

LAND_USE_IMPACT = {
    "EROSION_AREA_FACTOR": 0.5,
    "EROSION_AREA_FACTOR_CLEARING": 0.8,
    "SOIL_TIME_FACTOR": 1.5,
    "SOIL_TIME_FACTOR_CLEARING": 2.0,
    "HABITAT_AREA_FACTOR": 2.0,
    "HABITAT_AREA_FACTOR_CLEARING": 3.0,
    "WATER_TIME_FACTOR": 1.2,
    "WATER_TIME_FACTOR_CLEARING": 1.8,
    "MAX_PERCENTAGE": 95,
    "MAX_DEGRADATION": 80,
}

COMPARISON_FACTORS = {
    "CAR_EMISSIONS_PER_YEAR": 4600,
    "FLIGHT_NY_LONDON": 986,
    "HOUSEHOLD_ELECTRICITY_PER_YEAR": 7500,
}

SIMULATOR_VERSION = "1.1.0"
